spring:
  jackson:
  deserialization:
  fail-on-unknown-properties: false

server:
  servlet:
    context-path: /exchange

exchange:
  initial:
    one: 100
    five: 100
    ten: 100
    twenty-five: 100
  currency-type: USD

rates:
  base-uri: https://api.exchangeratesapi.io
  symbols: USD, CAD, GBP, EUR

validator:
  amount: 1,2, 5, 10, 20, 50, 100
  currency-code: USD, CAD, GBP, EUR